// Serviço de banco de dados de alimentos (mock para MVP)

import { Food } from '../types';
import { storage } from './storage';

// Base de dados mock de alimentos (em produção, viria de uma API)
const MOCK_FOODS: Food[] = [
  {
    id: '1',
    name: 'Arroz branco cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    iron: 0.8,
    folicAcid: 3,
    calcium: 10,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 1,
  },
  {
    id: '2',
    name: 'Feijão preto cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    iron: 2.1,
    folicAcid: 149,
    calcium: 27,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 2,
  },
  {
    id: '3',
    name: 'Frango grelhado',
    servingSize: 100,
    servingUnit: 'g',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    iron: 0.9,
    folicAcid: 4,
    calcium: 15,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 74,
  },
  {
    id: '4',
    name: 'Espinafre cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.4,
    iron: 3.6,
    folicAcid: 146,
    calcium: 136,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 8.4,
    sodium: 70,
  },
  {
    id: '5',
    name: 'Salmão grelhado',
    servingSize: 100,
    servingUnit: 'g',
    calories: 206,
    protein: 25.4,
    carbs: 0,
    fat: 12,
    fiber: 0,
    iron: 0.8,
    folicAcid: 25,
    calcium: 12,
    omega3: 2260,
    vitaminD: 11.8,
    vitaminC: 0,
    sodium: 44,
  },
  {
    id: '6',
    name: 'Leite integral',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 124,
    protein: 6.4,
    carbs: 9.6,
    fat: 6.4,
    fiber: 0,
    iron: 0.1,
    folicAcid: 5,
    calcium: 240,
    omega3: 0,
    vitaminD: 2.4,
    vitaminC: 0,
    sodium: 100,
  },
  {
    id: '7',
    name: 'Banana',
    servingSize: 100,
    servingUnit: 'g',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    iron: 0.3,
    folicAcid: 20,
    calcium: 5,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 8.7,
    sodium: 1,
  },
  {
    id: '8',
    name: 'Ovo cozido',
    servingSize: 50,
    servingUnit: 'unidade',
    calories: 78,
    protein: 6.3,
    carbs: 0.6,
    fat: 5.3,
    fiber: 0,
    iron: 0.9,
    folicAcid: 22,
    calcium: 25,
    omega3: 0,
    vitaminD: 1.1,
    vitaminC: 0,
    sodium: 62,
  },
  {
    id: '9',
    name: 'Aveia em flocos',
    servingSize: 30,
    servingUnit: 'g',
    calories: 110,
    protein: 4.3,
    carbs: 19.5,
    fat: 2.1,
    fiber: 2.8,
    iron: 1.2,
    folicAcid: 8,
    calcium: 28,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 1,
  },
  {
    id: '10',
    name: 'Iogurte natural',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 120,
    protein: 8,
    carbs: 10,
    fat: 4,
    fiber: 0,
    iron: 0.1,
    folicAcid: 12,
    calcium: 240,
    omega3: 0,
    vitaminD: 0.2,
    vitaminC: 0,
    sodium: 80,
  },
  {
    id: '11',
    name: 'Queijo minas frescal',
    servingSize: 50,
    servingUnit: 'g',
    calories: 90,
    protein: 6.5,
    carbs: 1.5,
    fat: 6,
    fiber: 0,
    iron: 0.1,
    folicAcid: 5,
    calcium: 200,
    omega3: 0,
    vitaminD: 0.1,
    vitaminC: 0,
    sodium: 180,
  },
  {
    id: '12',
    name: 'Brócolis cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 25,
    protein: 2.8,
    carbs: 4.5,
    fat: 0.4,
    fiber: 2.6,
    iron: 0.8,
    folicAcid: 63,
    calcium: 47,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 64.9,
    sodium: 33,
  },
  {
    id: '13',
    name: 'Lentilha cozida',
    servingSize: 100,
    servingUnit: 'g',
    calories: 116,
    protein: 9.1,
    carbs: 20.1,
    fat: 0.4,
    fiber: 7.9,
    iron: 3.3,
    folicAcid: 181,
    calcium: 19,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 1.5,
    sodium: 2,
  },
  {
    id: '14',
    name: 'Abacate',
    servingSize: 100,
    servingUnit: 'g',
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    iron: 0.6,
    folicAcid: 81,
    calcium: 12,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 10,
    sodium: 7,
  },
  {
    id: '15',
    name: 'Batata doce assada',
    servingSize: 100,
    servingUnit: 'g',
    calories: 90,
    protein: 1.6,
    carbs: 21.3,
    fat: 0.1,
    fiber: 3.3,
    iron: 0.6,
    folicAcid: 11,
    calcium: 30,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 20.1,
    sodium: 54,
  },
  {
    id: '16',
    name: 'Peito de peru',
    servingSize: 50,
    servingUnit: 'g',
    calories: 60,
    protein: 12,
    carbs: 1,
    fat: 0.5,
    fiber: 0,
    iron: 0.8,
    folicAcid: 3,
    calcium: 5,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 550,
  },
  {
    id: '17',
    name: 'Mamão papaia',
    servingSize: 100,
    servingUnit: 'g',
    calories: 43,
    protein: 0.5,
    carbs: 11,
    fat: 0.1,
    fiber: 1.8,
    iron: 0.3,
    folicAcid: 37,
    calcium: 20,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 60.9,
    sodium: 3,
  },
  {
    id: '18',
    name: 'Castanha do Pará',
    servingSize: 10,
    servingUnit: 'unidades',
    calories: 65,
    protein: 1.4,
    carbs: 1.3,
    fat: 6.6,
    fiber: 0.7,
    iron: 0.4,
    folicAcid: 1,
    calcium: 16,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 1,
  },
  {
    id: '19',
    name: 'Couve refogada',
    servingSize: 100,
    servingUnit: 'g',
    calories: 90,
    protein: 2.9,
    carbs: 4.3,
    fat: 7.2,
    fiber: 2.9,
    iron: 1.7,
    folicAcid: 194,
    calcium: 131,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 108.9,
    sodium: 15,
  },
  {
    id: '20',
    name: 'Atum em conserva',
    servingSize: 100,
    servingUnit: 'g',
    calories: 166,
    protein: 26,
    carbs: 0,
    fat: 6,
    fiber: 0,
    iron: 1.2,
    folicAcid: 2,
    calcium: 12,
    omega3: 1080,
    vitaminD: 2.8,
    vitaminC: 0,
    sodium: 396,
  },
  {
    id: '21',
    name: 'Açaí (polpa)',
    servingSize: 100,
    servingUnit: 'g',
    calories: 58,
    protein: 0.8,
    carbs: 6.2,
    fat: 3.9,
    fiber: 2.6,
    iron: 0.6,
    folicAcid: 6,
    calcium: 118,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 9.6,
    sodium: 6,
  },
  {
    id: '22',
    name: 'Tofu',
    servingSize: 100,
    servingUnit: 'g',
    calories: 76,
    protein: 8.1,
    carbs: 1.9,
    fat: 4.2,
    fiber: 0.3,
    iron: 1.9,
    folicAcid: 15,
    calcium: 130,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 7,
  },
  {
    id: '23',
    name: 'Manga',
    servingSize: 100,
    servingUnit: 'g',
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    iron: 0.1,
    folicAcid: 14,
    calcium: 11,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 36.4,
    sodium: 1,
  },
  {
    id: '24',
    name: 'Aveia',
    servingSize: 30,
    servingUnit: 'g',
    calories: 110,
    protein: 4.3,
    carbs: 19.5,
    fat: 2.1,
    fiber: 2.8,
    iron: 1.2,
    folicAcid: 8,
    calcium: 28,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 1,
  },
  {
    id: '25',
    name: 'Granola',
    servingSize: 30,
    servingUnit: 'g',
    calories: 120,
    protein: 3,
    carbs: 22,
    fat: 3,
    fiber: 2.5,
    iron: 1.5,
    folicAcid: 10,
    calcium: 30,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 85,
  },
  {
    id: '26',
    name: 'Pão integral',
    servingSize: 50,
    servingUnit: 'fatia',
    calories: 120,
    protein: 5,
    carbs: 22,
    fat: 2,
    fiber: 3.5,
    iron: 1.8,
    folicAcid: 25,
    calcium: 40,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 250,
  },
  {
    id: '27',
    name: 'Macarrão integral cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 124,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 3.2,
    iron: 1.2,
    folicAcid: 18,
    calcium: 20,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 1,
  },
  {
    id: '28',
    name: 'Carne bovina magra grelhada',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    iron: 2.6,
    folicAcid: 6,
    calcium: 8,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 55,
  },
  {
    id: '29',
    name: 'Tomate',
    servingSize: 100,
    servingUnit: 'g',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    iron: 0.3,
    folicAcid: 15,
    calcium: 10,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 13.7,
    sodium: 5,
  },
  {
    id: '30',
    name: 'Cenoura cozida',
    servingSize: 100,
    servingUnit: 'g',
    calories: 30,
    protein: 0.8,
    carbs: 7.2,
    fat: 0.2,
    fiber: 2.8,
    iron: 0.3,
    folicAcid: 14,
    calcium: 33,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 3.6,
    sodium: 69,
  },
  // Pães
  {
    id: '31',
    name: 'Pão francês',
    servingSize: 50,
    servingUnit: 'unidade',
    calories: 135,
    protein: 4.2,
    carbs: 26,
    fat: 1.5,
    fiber: 1.2,
    iron: 1.2,
    folicAcid: 15,
    calcium: 20,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 300,
  },
  {
    id: '32',
    name: 'Pão de forma',
    servingSize: 25,
    servingUnit: 'fatia',
    calories: 70,
    protein: 2.2,
    carbs: 13,
    fat: 0.8,
    fiber: 0.8,
    iron: 0.8,
    folicAcid: 12,
    calcium: 15,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 180,
  },
  {
    id: '33',
    name: 'Pão italiano',
    servingSize: 50,
    servingUnit: 'fatia',
    calories: 140,
    protein: 4.5,
    carbs: 27,
    fat: 1.2,
    fiber: 1.5,
    iron: 1.5,
    folicAcid: 18,
    calcium: 25,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 350,
  },
  {
    id: '34',
    name: 'Pão de queijo',
    servingSize: 30,
    servingUnit: 'unidade',
    calories: 90,
    protein: 3.5,
    carbs: 10,
    fat: 4.2,
    fiber: 0.2,
    iron: 0.5,
    folicAcid: 5,
    calcium: 120,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 200,
  },
  // Massas
  {
    id: '35',
    name: 'Macarrão cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 130,
    protein: 4.5,
    carbs: 25,
    fat: 0.8,
    fiber: 1.2,
    iron: 0.8,
    folicAcid: 12,
    calcium: 8,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 2,
  },
  {
    id: '36',
    name: 'Arroz integral cozido',
    servingSize: 100,
    servingUnit: 'g',
    calories: 124,
    protein: 2.6,
    carbs: 25.8,
    fat: 1,
    fiber: 1.8,
    iron: 0.6,
    folicAcid: 4,
    calcium: 8,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 1,
  },
  // Carnes
  {
    id: '37',
    name: 'Carne bovina grelhada',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    iron: 2.6,
    folicAcid: 6,
    calcium: 8,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 55,
  },
  {
    id: '38',
    name: 'Peixe grelhado',
    servingSize: 100,
    servingUnit: 'g',
    calories: 180,
    protein: 24,
    carbs: 0,
    fat: 8,
    fiber: 0,
    iron: 1.2,
    folicAcid: 8,
    calcium: 20,
    omega3: 1200,
    vitaminD: 5.2,
    vitaminC: 0,
    sodium: 50,
  },
  // Molhos
  {
    id: '39',
    name: 'Molho branco',
    servingSize: 50,
    servingUnit: 'ml',
    calories: 120,
    protein: 2.5,
    carbs: 5,
    fat: 9,
    fiber: 0.2,
    iron: 0.2,
    folicAcid: 2,
    calcium: 80,
    omega3: 0,
    vitaminD: 0.5,
    vitaminC: 0,
    sodium: 250,
  },
  {
    id: '40',
    name: 'Molho de tomate',
    servingSize: 100,
    servingUnit: 'g',
    calories: 35,
    protein: 1.2,
    carbs: 7,
    fat: 0.3,
    fiber: 1.5,
    iron: 0.8,
    folicAcid: 12,
    calcium: 15,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 15,
    sodium: 400,
  },
  {
    id: '41',
    name: 'Maionese',
    servingSize: 15,
    servingUnit: 'g',
    calories: 110,
    protein: 0.3,
    carbs: 0.5,
    fat: 12,
    fiber: 0,
    iron: 0.1,
    folicAcid: 0,
    calcium: 2,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 80,
  },
  // Verduras e Legumes
  {
    id: '42',
    name: 'Alface',
    servingSize: 50,
    servingUnit: 'g',
    calories: 7,
    protein: 0.5,
    carbs: 1.2,
    fat: 0.1,
    fiber: 1,
    iron: 0.5,
    folicAcid: 38,
    calcium: 18,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 5,
    sodium: 4,
  },
  {
    id: '43',
    name: 'Rúcula',
    servingSize: 50,
    servingUnit: 'g',
    calories: 12,
    protein: 1.2,
    carbs: 1.5,
    fat: 0.2,
    fiber: 1.2,
    iron: 1.5,
    folicAcid: 97,
    calcium: 160,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 15,
    sodium: 27,
  },
  {
    id: '44',
    name: 'Cebola',
    servingSize: 50,
    servingUnit: 'g',
    calories: 20,
    protein: 0.5,
    carbs: 4.5,
    fat: 0.1,
    fiber: 0.8,
    iron: 0.2,
    folicAcid: 9,
    calcium: 12,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 4,
    sodium: 2,
  },
  // Doces e Lanches
  {
    id: '45',
    name: 'Chocolate ao leite',
    servingSize: 30,
    servingUnit: 'g',
    calories: 160,
    protein: 2.5,
    carbs: 18,
    fat: 9,
    fiber: 1.2,
    iron: 0.8,
    folicAcid: 3,
    calcium: 60,
    omega3: 0,
    vitaminD: 0.2,
    vitaminC: 0,
    sodium: 25,
  },
  {
    id: '46',
    name: 'Bolacha recheada',
    servingSize: 30,
    servingUnit: 'g',
    calories: 150,
    protein: 2,
    carbs: 20,
    fat: 7,
    fiber: 0.5,
    iron: 0.5,
    folicAcid: 2,
    calcium: 10,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 120,
  },
  {
    id: '47',
    name: 'Pão de mel',
    servingSize: 50,
    servingUnit: 'unidade',
    calories: 180,
    protein: 3,
    carbs: 32,
    fat: 5,
    fiber: 1.5,
    iron: 1.2,
    folicAcid: 8,
    calcium: 25,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 150,
  },
  // Pizzas
  {
    id: '48',
    name: 'Pizza de mussarela',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    protein: 12,
    carbs: 28,
    fat: 10,
    fiber: 1.5,
    iron: 1.5,
    folicAcid: 15,
    calcium: 200,
    omega3: 0,
    vitaminD: 0.3,
    vitaminC: 2,
    sodium: 550,
  },
  {
    id: '49',
    name: 'Pizza de calabresa',
    servingSize: 100,
    servingUnit: 'g',
    calories: 280,
    protein: 13,
    carbs: 28,
    fat: 13,
    fiber: 1.5,
    iron: 1.8,
    folicAcid: 15,
    calcium: 180,
    omega3: 0,
    vitaminD: 0.3,
    vitaminC: 2,
    sodium: 750,
  },
  {
    id: '50',
    name: 'Pizza portuguesa',
    servingSize: 100,
    servingUnit: 'g',
    calories: 270,
    protein: 14,
    carbs: 28,
    fat: 12,
    fiber: 2,
    iron: 2,
    folicAcid: 18,
    calcium: 190,
    omega3: 0,
    vitaminD: 0.3,
    vitaminC: 3,
    sodium: 680,
  },
  {
    id: '51',
    name: 'Pizza de calabresa com queijo',
    servingSize: 100,
    servingUnit: 'g',
    calories: 290,
    protein: 14,
    carbs: 28,
    fat: 14,
    fiber: 1.5,
    iron: 1.8,
    folicAcid: 16,
    calcium: 200,
    omega3: 0,
    vitaminD: 0.3,
    vitaminC: 2,
    sodium: 780,
  },
  {
    id: '52',
    name: 'Pizza de calabresa com requeijão',
    servingSize: 100,
    servingUnit: 'g',
    calories: 300,
    protein: 15,
    carbs: 28,
    fat: 15,
    fiber: 1.5,
    iron: 1.8,
    folicAcid: 17,
    calcium: 220,
    omega3: 0,
    vitaminD: 0.3,
    vitaminC: 2,
    sodium: 800,
  },
  {
    id: '53',
    name: 'Pizza quatro queijos',
    servingSize: 100,
    servingUnit: 'g',
    calories: 290,
    protein: 16,
    carbs: 28,
    fat: 13,
    fiber: 1.5,
    iron: 1.6,
    folicAcid: 18,
    calcium: 280,
    omega3: 0,
    vitaminD: 0.4,
    vitaminC: 1,
    sodium: 650,
  },
  // Hambúrgueres
  {
    id: '54',
    name: 'Hambúrguer',
    servingSize: 100,
    servingUnit: 'g',
    calories: 250,
    protein: 15,
    carbs: 25,
    fat: 10,
    fiber: 1.5,
    iron: 2,
    folicAcid: 12,
    calcium: 50,
    omega3: 0,
    vitaminD: 0.1,
    vitaminC: 0,
    sodium: 450,
  },
  {
    id: '55',
    name: 'Hambúrguer com queijo',
    servingSize: 120,
    servingUnit: 'g',
    calories: 320,
    protein: 18,
    carbs: 28,
    fat: 14,
    fiber: 1.8,
    iron: 2.2,
    folicAcid: 15,
    calcium: 180,
    omega3: 0,
    vitaminD: 0.2,
    vitaminC: 0,
    sodium: 580,
  },
  {
    id: '56',
    name: 'Hambúrguer com queijo e bacon',
    servingSize: 140,
    servingUnit: 'g',
    calories: 380,
    protein: 20,
    carbs: 28,
    fat: 20,
    fiber: 1.8,
    iron: 2.4,
    folicAcid: 16,
    calcium: 190,
    omega3: 0,
    vitaminD: 0.2,
    vitaminC: 0,
    sodium: 750,
  },
  // Frutas
  {
    id: '57',
    name: 'Melancia',
    servingSize: 150,
    servingUnit: 'g',
    calories: 45,
    protein: 0.9,
    carbs: 11,
    fat: 0.2,
    fiber: 0.5,
    iron: 0.2,
    folicAcid: 3,
    calcium: 8,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 8.1,
    sodium: 1,
  },
  {
    id: '58',
    name: 'Melão',
    servingSize: 150,
    servingUnit: 'g',
    calories: 34,
    protein: 0.8,
    carbs: 8.2,
    fat: 0.2,
    fiber: 0.8,
    iron: 0.2,
    folicAcid: 21,
    calcium: 11,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 36.7,
    sodium: 16,
  },
  {
    id: '59',
    name: 'Laranja',
    servingSize: 150,
    servingUnit: 'g',
    calories: 62,
    protein: 1.2,
    carbs: 15,
    fat: 0.2,
    fiber: 2.4,
    iron: 0.2,
    folicAcid: 40,
    calcium: 40,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 53.2,
    sodium: 0,
  },
  {
    id: '60',
    name: 'Uva',
    servingSize: 100,
    servingUnit: 'g',
    calories: 69,
    protein: 0.7,
    carbs: 17,
    fat: 0.2,
    fiber: 0.9,
    iron: 0.4,
    folicAcid: 2,
    calcium: 10,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 3.2,
    sodium: 3,
  },
  // Bebidas
  {
    id: '61',
    name: 'Refrigerante',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 85,
    protein: 0,
    carbs: 21,
    fat: 0,
    fiber: 0,
    iron: 0,
    folicAcid: 0,
    calcium: 0,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 0,
    sodium: 8,
  },
  // Doces
  {
    id: '62',
    name: 'Sonho',
    servingSize: 60,
    servingUnit: 'unidade',
    calories: 220,
    protein: 4,
    carbs: 28,
    fat: 10,
    fiber: 0.8,
    iron: 0.6,
    folicAcid: 5,
    calcium: 30,
    omega3: 0,
    vitaminD: 0.1,
    vitaminC: 0,
    sodium: 150,
  },
  // Laticínios e Gorduras
  {
    id: '63',
    name: 'Manteiga',
    servingSize: 10,
    servingUnit: 'g',
    calories: 75,
    protein: 0.1,
    carbs: 0,
    fat: 8.3,
    fiber: 0,
    iron: 0,
    folicAcid: 0,
    calcium: 2,
    omega3: 0,
    vitaminD: 0.1,
    vitaminC: 0,
    sodium: 1,
  },
  {
    id: '64',
    name: 'Requeijão',
    servingSize: 30,
    servingUnit: 'g',
    calories: 85,
    protein: 3.5,
    carbs: 2,
    fat: 6.5,
    fiber: 0,
    iron: 0.1,
    folicAcid: 3,
    calcium: 90,
    omega3: 0,
    vitaminD: 0.2,
    vitaminC: 0,
    sodium: 200,
  },
  // Sucos
  {
    id: '65',
    name: 'Suco de uva',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 120,
    protein: 0.5,
    carbs: 28,
    fat: 0.2,
    fiber: 0.3,
    iron: 0.3,
    folicAcid: 2,
    calcium: 12,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 2.5,
    sodium: 5,
  },
  {
    id: '66',
    name: 'Suco de laranja',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 90,
    protein: 1.5,
    carbs: 20,
    fat: 0.2,
    fiber: 0.5,
    iron: 0.2,
    folicAcid: 50,
    calcium: 50,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 70,
    sodium: 1,
  },
  {
    id: '67',
    name: 'Suco de melancia',
    servingSize: 200,
    servingUnit: 'ml',
    calories: 60,
    protein: 1,
    carbs: 14,
    fat: 0.2,
    fiber: 0.3,
    iron: 0.2,
    folicAcid: 3,
    calcium: 10,
    omega3: 0,
    vitaminD: 0,
    vitaminC: 10,
    sodium: 2,
  },
];

/**
 * Busca alimentos por nome (simulação de busca com autocompletar)
 * Inclui alimentos da base mock e alimentos customizados do usuário
 */
export async function searchFoods(query: string): Promise<Food[]> {
  if (!query.trim()) return [];

  const lowerQuery = query.toLowerCase();
  
  // Buscar em alimentos mock
  const mockResults = MOCK_FOODS.filter(
    (food) =>
      food.name.toLowerCase().includes(lowerQuery) ||
      (food.brand && food.brand.toLowerCase().includes(lowerQuery))
  );

  // Buscar em alimentos customizados
  try {
    const customFoods = await storage.getCustomFoods();
    const customResults = customFoods.filter(
      (food: Food) =>
        food.name.toLowerCase().includes(lowerQuery) ||
        (food.brand && food.brand.toLowerCase().includes(lowerQuery))
    );

    // Combinar resultados (customizados primeiro)
    return [...customResults, ...mockResults];
  } catch (error) {
    console.error('Erro ao buscar alimentos customizados:', error);
    return mockResults;
  }
}

/**
 * Busca um alimento por ID
 */
export async function getFoodById(id: string): Promise<Food | null> {
  return MOCK_FOODS.find((food) => food.id === id) || null;
}

/**
 * Busca um alimento por código de barras (mock)
 */
export async function getFoodByBarcode(barcode: string): Promise<Food | null> {
  // Em produção, isso faria uma chamada à API
  return MOCK_FOODS.find((food) => food.barcode === barcode) || null;
}

/**
 * Retorna alimentos favoritos (mock)
 */
export async function getFavoriteFoods(): Promise<Food[]> {
  // Em produção, isso viria do storage do usuário
  return [];
}

/**
 * Adiciona um alimento customizado
 */
export async function addCustomFood(food: Food): Promise<Food> {
  try {
    const customFoods = await storage.getCustomFoods();
    
    // Verificar se já existe um alimento com o mesmo nome
    const existing = customFoods.find((f: Food) => f.name.toLowerCase() === food.name.toLowerCase());
    if (existing) {
      throw new Error('Já existe um alimento com este nome');
    }

    // Adicionar ID único se não tiver
    const newFood: Food = {
      ...food,
      id: food.id || `custom_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    };

    customFoods.push(newFood);
    await storage.saveCustomFoods(customFoods);
    
    return newFood;
  } catch (error) {
    console.error('Erro ao adicionar alimento customizado:', error);
    throw error;
  }
}

